"""phase 5: add session_key to user_sessions for sid-claim session identification

Revision ID: 12ba92ef9119
Revises: d57f7940d777
Create Date: 2026-07-22 13:10:14.482572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ba92ef9119'
down_revision = 'd57f7940d777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_key', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_sessions_session_key'), ['session_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_session_key'))
        batch_op.drop_column('session_key')

    # ### end Alembic commands ###
