"""phase 9 active protection: blocked_websites table, protection_mode setting

Revision ID: 396d35d5a290
Revises: ec2bbce90d8a
Create Date: 2026-07-25 11:31:36.211897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '396d35d5a290'
down_revision = 'ec2bbce90d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scanner_type', sa.String(length=16), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(), nullable=False),
    sa.Column('unblocked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', name='uq_blocked_websites_user_domain')
    )
    with op.batch_alter_table('blocked_websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_websites_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_websites_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_websites_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        # server_default required: user_settings already has rows (existing
        # users), and Postgres rejects a NOT NULL column added to a non-empty
        # table without one (see the Phase 7 migration notes in the README).
        batch_op.add_column(sa.Column('protection_mode', sa.String(length=32), nullable=False, server_default='warn_only'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('protection_mode')

    with op.batch_alter_table('blocked_websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_websites_user_id'))
        batch_op.drop_index(batch_op.f('ix_blocked_websites_is_active'))
        batch_op.drop_index(batch_op.f('ix_blocked_websites_domain'))

    op.drop_table('blocked_websites')
    # ### end Alembic commands ###
