"""Add scan history and blacklist tables

Revision ID: 4510943deac3
Revises: 9929dee9046c
Create Date: 2026-07-21 12:55:05.026789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4510943deac3'
down_revision = '9929dee9046c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('added_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_entries_domain'), ['domain'], unique=True)

    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('scan_result', sa.JSON(), nullable=False),
    sa.Column('analysis_details', sa.JSON(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_history_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_scan_date'), ['scan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_history_scan_date'))
        batch_op.drop_index(batch_op.f('ix_scan_history_risk_level'))

    op.drop_table('scan_history')
    with op.batch_alter_table('blacklist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_entries_domain'))

    op.drop_table('blacklist_entries')
    # ### end Alembic commands ###
