"""Add email scan history table

Revision ID: c1c6ec70cefc
Revises: 177cff4e01fb
Create Date: 2026-07-21 17:19:40.534596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1c6ec70cefc'
down_revision = '177cff4e01fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sender_display_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('link_count', sa.Integer(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('scan_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_scan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_scan_history_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_scan_history_scan_date'), ['scan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_scan_history_sender_email'), ['sender_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_scan_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_scan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_scan_history_sender_email'))
        batch_op.drop_index(batch_op.f('ix_email_scan_history_scan_date'))
        batch_op.drop_index(batch_op.f('ix_email_scan_history_risk_level'))

    op.drop_table('email_scan_history')
    # ### end Alembic commands ###
