"""Admin: user status field and user_restrictions table

Revision ID: c362fb36e69c
Revises: b7c1e4d9a3f6
Create Date: 2026-08-11 16:57:23.831551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c362fb36e69c'
down_revision = 'b7c1e4d9a3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('feature', sa.String(length=16), nullable=False),
    sa.Column('restricted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('restricted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restricted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature', name='uq_user_restrictions_user_feature')
    )
    with op.batch_alter_table('user_restrictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_restrictions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=False, server_default='active'))

    # ### end Alembic commands ###

    # Backfill: any account already deactivated before this migration (via
    # the pre-existing is_active flag) should read as "suspended", not the
    # column default of "active" — keeps the two fields consistent for rows
    # that predate `status`.
    op.execute("UPDATE users SET status = 'suspended' WHERE is_active = false")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('user_restrictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_restrictions_user_id'))

    op.drop_table('user_restrictions')
    # ### end Alembic commands ###
