"""Add QR scan history table

Revision ID: da63d791cb98
Revises: c1c6ec70cefc
Create Date: 2026-07-22 11:12:09.658146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da63d791cb98'
down_revision = 'c1c6ec70cefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('raw_content', sa.String(length=2048), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('scan_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_scan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_scan_history_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_scan_history_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_scan_history_scan_date'), ['scan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_scan_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_scan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_qr_scan_history_scan_date'))
        batch_op.drop_index(batch_op.f('ix_qr_scan_history_risk_level'))
        batch_op.drop_index(batch_op.f('ix_qr_scan_history_content_type'))

    op.drop_table('qr_scan_history')
    # ### end Alembic commands ###
